// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eauupydshoidelyrrbaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdXVweWRzaG9pZGVseXJyYmFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNzk2OTEsImV4cCI6MjA4OTk1NTY5MX0.6Ux0aQuyCbZYDUHjFuDI_j9KEy1DvUo6u2BcB1VTWQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
